### Option:Plugins.NVIDIA.System.Path
#	Path to loadable plugin executable.
#
# Mandatory: yes
# Default:
# Plugins.NVIDIA.System.Path=

### Option: Plugins.NVIDIA.Timeout
#   Legacy fallback timeout value. Amount of time to wait for a server to respond when first connecting and on
#   follow up operations in the session.
#
#   This value is only used for item checks coming from Zabbix server
#   versions older than 7.0. For newer versions, item check timeout can be
#   configured in the frontend.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.NVIDIA.Timeout=<Global timeout>
