### Option:Plugins.NVIDIA.System.Path
#	Path to external plugin executable.
#
# Mandatory: yes
# Default:
# Plugins.NVIDIA.System.Path=

### Option: Plugins.NVIDIA.Timeout
#	Example of a default timeout set in configuration if not , timeout for my ip call
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.NVIDIA.Timeout=<Global timeout>
