### Option:Plugins.NVIDIA.System.Path
#	Path to loadable plugin executable.
#
# Mandatory: yes
# Default:
# Plugins.NVIDIA.System.Path=

### Option: Plugins.NVIDIA.Timeout
#	Plugin connection timeout.
#
# Mandatory: no
# Range: 1-30
# Default:
# Plugins.NVIDIA.Timeout=<Global timeout>
